openapi: 3.0.3
info:
  title: INTE PDP Components
  description: OAS Components acting as a contract for data published by INTE to PDP.
  version: v1.3.0
paths: { }
components:
  schemas:
    # Angebotsportfolio-Tool
    Konzept:
      description: "Konzept aka Angebot aka Campaign defined in Angebotsportfolio-Tool which also is the Master for Konzept-IDs."
      type: object
      required: [ id, bezeichnung ]
      properties:
        id:
          type: string
          example: "A00104"
          description: "Konzept-ID aka Angebots-ID aka Offer-ID."
        bezeichnung:
          type: string
          example: "Echo der Zeit"
          description: "Official name of the Konzept."
        unternehmenseinheit:
          type: string
          example: "SRF"
          description: "Organisational unit that has the ownership."
        statusName:
          type: string
          example: "Publiziert / Laufend"
          description: "Status des Angebots"
        sendungenABisZ:
          type: boolean
          description: "Soll Sendung in A-Z Liste erscheinen"
        kurzbeschreibung:
          type: string
          example: "«Echo der Zeit» ist die älteste politische Hintergrundsendung von Radio SRF: Seit 1945 vermittelt 
                    die Sendung täglich die wichtigsten Nachrichten, Berichte, Reportagen, Interviews und Analysen über 
                    das aktuelle Zeitgeschehen"
          description: "Short description of the Konzept."
        vermarktungen:
          type: array
          items:
            $ref: "#/components/schemas/KonzeptVermarktung"

    KonzeptVermarktung:
      description: "Describes for which channels and at which schedules the Sendungen of a Konzept are planned to be published."
      type: object
      required: [ publikationskanalId ]
      properties:
        publikationskanalId:
          type: string
          example: "K00004"
          description: "Reference to Kanal by ID."
        publikationsregeln:
          type: array
          items:
            $ref: "#/components/schemas/KonzeptPublikationsregel"

    KonzeptPublikationskanal:
      description: "A publication-channel of SRF or a third party."
      type: object
      required: [ id, bezeichnung ]
      properties:
        id:
          type: string
          example: "K00004"
          description: "Unique ID."
        bezeichnung:
          type: string
          example: "Radio SRF 1@Radio"
          description: "Official name of the channel."
        unternehmenseinheit:
          type: string
          example: "SRF"
          description: "Organisational unit that has the ownership."
        vektor:
          $ref: "#/components/schemas/PublicationVector"

    KonzeptPublikationsregel:
      description: "Publication rule defining when a Konzept is planned to be published and optionally in which interval."
      type: object
      properties:
        start:
          type: string
          format: date
          example: "2023-07-21"
          description: "Date at which the first publication is planned."
        ende:
          type: string
          format: date
          example: "2030-07-21"
          description: "Date at which the last publication is planned."
        zeit:
          type: string
          format: "HH:mm"
          example: "17:30"
          description: "Time within a day at which publications are planned."
        dauerInMin:
          type: integer
          example: "43"
          description: "Duration in minutes a publication usually will take."
        wiederholungByDay:
          type: array
          items:
            $ref: "#/components/schemas/DayOfWeek"
        wiederholungByMonth:
          type: array
          items:
            $ref: "#/components/schemas/Month"
        wiederholungByMonthWeek:
          type: array
          items:
            type: integer
          description: "Planned frequency for repetition in month-weeks. E.g. every 2nd week in a month. If combined with 'wiederholungByDay' the meaning would be e.g. 'every 2nd Monday of a month'"
        wiederholungByMonthDay:
          type: array
          items:
            type: integer
        wiederholungsrateMinutes:
          type: integer
          example: "30"
          description: "Planned frequency for repetition in minutes. E.g. every 30 minutes."
        wiederholungsrateDays:
          type: integer
          example: "3"
          description: "Planned frequency for repetition in days. E.g. every 3 days."
        wiederholungsrateWeeks:
          type: integer
          example: "2"
          description: "Planned frequency for repetition in weeks. E.g. every 2 weeks."
        wiederholungsrateMonths:
          type: integer
          example: "6"
          description: "Planned frequency for repetition in months. E.g. every 6 months."
        erstausstrahlung:
          type: boolean
          example: "true"
          description: "Indicates whether this publication rule concerns the first publication or not."
        ausnahmen:
          type: array
          description: "Specific dates at which a Sendung of the Konzept shall not be published."
          items:
            type: string
            format: date
            example: "2023-10-11"

    # OpenMedia
    OpenMediaRunning:
      description: "Running aka Episode aka Program planned in OpenMedia. Internally OpenMedia uses the term Document for this Domain-Object."
      type: object
      required: [ id, konzeptId, produktId, titel, lead, moderation ]
      properties:
        id:
          type: string
          example: "urn:openmedia:25647147-2092-4535-a503-3db038ec7ecb:000000020088F056"
          description: "Unique local identifier within OpenMedia."
        konzeptId:
          type: string
          example: "A00397"
          description: "Konzept-ID aka Angebots-ID aka Offer-ID."
        produktId:
          type: string
          example: "AUDI20230623_RS_0015"
          description: "Produktions-ID that OpenMedia retrieved from Digas by a look up with the Konzept-ID."
        maturityLevel:
          $ref: '#/components/schemas/MaturityLevel'
        titel:
          type: string
          example: "Das passende Kopfkissen finden"
          description: "Title of the story."
        lead:
          type: string
          example: "Das Kopfkissen sollte nicht nur kuschelig sein, sondern in erster Linie Kopf und Nacken stützen."
          description: "Lead aka headline of the story."
        produzent:
          type: string
          example: "Maria Kressbach"
          description: "Name of the producer."
        moderation:
          type: string
          example: "Stefan Siegenthaler"
          description: "Name of the host."
        geplantePublikationszeit:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The planned publication date and time in UTC."
        episodenlauftext:
          type: string
          example: "... langer text ..."
          description: "moderation text"
        image:
          $ref: '#/components/schemas/RokkaIoImage'
        urls:
          type: array
          items:
            type: string
            example: "https://www.srf.ch/audio/ratgeber"
            description: "url"
        publicationType:
          $ref: '#/components/schemas/PublicationType'
        beitraege:
          type: array
          items:
            $ref: '#/components/schemas/OpenMediaRunningBeitrag'
        assets:
          type: array
          items:
            $ref: '#/components/schemas/OpenMediaRunningAsset'

    OpenMediaRunningBeitrag:
      description: "Part of a OpenMediaRunning"
      type: object
      required: [produktElementId, titel, lead ]
      properties:
        produktElementId:
          type: string
          example: "AUDI20230829_RS_0031_0002"
        titel:
          type: string
          example: "Libyens Trauma nach den Fluten"
          description: "Title of the story"
        lead:
          type: string
          example: "Vor einer Woche fegte ein gewaltiger Sturm über die ostlibysche Küste..."
          description: "Lead of the story"
        image:
          $ref: '#/components/schemas/RokkaIoImage'

    OpenMediaRunningAsset:
      description: "Media assets belonging to a Running of OpenMedia."
      type: object
      required:
        - titel
        - dateiname
        - url
      properties:
        titel:
          type: string
          example: "Kopfkissen Deluxe"
          description: "Title for the media asset."
        description:
          type: string
          example: "Mann stuetzt Kopf auf einem Wollkopfkissen."
          description: "Description for the media asset."
        source:
          type: string
          example: "https://www.theselfieco.com/"
          description: "Source from which the media asset was taken from."
        dateiname:
          type: string
          example: "kopfkissen-1337.png"
          description: "Original filename as stored on the file-system in OpenMedia."
        url:
          type: string
          example: "https://programmrastervorschau-stage.s3.eu-central-1.amazonaws.com/additional-assets/AUDI20230623_RS_0015/image/kopfkissen-1337.png"
          description: "URL to the storage (Amazon S3) INTE has uploaded the media asset to."

    # Audio
    DigasAudioFileMetadata:
      description: "Metadata about a published audio file"
      required: [ konzeptId, produktId, fassungsId, url, publicationType ]
      type: object
      properties:
        type:
          $ref: "#/components/schemas/MediaType"
        konzeptId:
          type: string
          example: "A00125"
        produktId:
          type: string
          example: "AUDI20230905_RS_0006"
        produktElementId:
          type: string
          example: "AUDI20230905_RS_0006_0002"
        fassungsId:
          type: string
          example: "AUDI20230905_RS_0006_APP_02"
        titel:
          type: string
          example: "Espresso"
          description: "Title representing the content of the media asset. Possibly not a public title."
        url:
          type: string
          example: "https://srf-media-storage-stage.s3.eu-central-1.amazonaws.com/incoming-audio/AUDI20230905_RS_0006/audio/AUDI20230905_RS_0006_APP_01.wav"
          description: "URL to the storage (Amazon S3) INTE has uploaded the media asset to."
        publicationType:
          $ref: '#/components/schemas/PublicationType'
        liveSendezeitStart:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The effective start time of a live publication in UTC. Only set for publicationType = 'LIVE'."
        liveSendezeitEnde:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The effective end time of a live publication in UTC. Only set for publicationType = 'LIVE'."

    RokkaIoImage:
      description: "Metadata about a image in rokka-io"
      type: object
      required: [ hash, url, format, title ]
      properties:
        hash:
          type: string
          example: "c412d8d6e4b9b7b058320b06972ac0ec72cfe6e5"
          description: "the identifier of the image in rokka-io"
        url:
          type: string
          example: "/sourceimages/mycompany/c412d8d6e4b9b7b058320b06972ac0ec72cfe6e5"
          description: "link to the image in rokka-io"
        format:
          type: string
          example: "png"
          description: "fileformat of the image"
        title:
          type: string
          example: "image1.png"
          description: "the filename of the image"

    # WhatsOn
    WhatsOnProdukt:
      description: "Produkt aka Program planned in WhatsOn."
      type: object
      required: [ id ]
      properties:
        id:
          type: string
          example: "10029"
          description: "Unique local ID of the Produkt in WhatsOn (Produkt-ID)."
        konzeptId:
          type: string
          example: "A00053"
          description: "Konzept-ID aka Angebots-ID aka Offer-ID."


    # Common
    PublicationType:
      type: string
      description: "The type of a publication."
      nullable: true
      enum:
        - FILE
        - LIVE


    MaturityLevel:
      type: string
      description: "The maturity of a OpenMediaRunning"
      nullable: false
      enum:
        - SENDEHINWEIS
        - ONLINEPUBLIKATION


    MediaType:
      type: string
      description: "Media File Type"
      nullable: false
      enum:
        - VIDEO
        - AUDIO

    PublicationVector:
      type: string
      description: "The vector for publication."
      nullable: true
      enum:
        - DIGITAL
        - PRINT
        - RADIO
        - TV

    DayOfWeek:
      type: string
      description: "Day of week."
      nullable: false
      enum:
        - MONDAY
        - TUESDAY
        - WEDNESDAY
        - THURSDAY
        - FRIDAY
        - SATURDAY
        - SUNDAY

    Month:
      type: string
      description: "Month"
      nullable: false
      enum:
        - JANUARY
        - FEBRUARY
        - MARCH
        - APRIL
        - MAY
        - JUNE
        - JULY
        - AUGUST
        - SEPTEMBER
        - OCTOBER
        - NOVEMBER
        - DECEMBER
