openapi: 3.0.3
info:
  title: INTE PDP Components for OpenMedia
  description: OAS Components acting as a contract for data published by INTE to PDP.
  version: 2.0.0
paths: { }
components:
  schemas:

    OpenMediaAudioProgram:
      description: "Running aka Episode aka Program planned in OpenMedia. Internally OpenMedia uses the term Document for this Domain-Object."
      type: object
      required: [ urn, konzeptId, produktId ]
      properties:
        urn:
          type: string
          example: "urn:openmedia:25647147-2092-4535-a503-3db038ec7ecb:000000020088F056"
          description: "Unique local identifier within OpenMedia."
        konzeptId:
          type: string
          example: "A00397"
          description: "Konzept-ID aka Angebots-ID aka Offer-ID."
        produktId:
          type: string
          example: "AUDI20230623_RS_0015"
          description: "Produktions-ID aka PID."
        fassungId:
          type: string
          example: "AUDI20240506_NR_0013_APP_02"
          description: "Fassung-ID generated during Online-Publication workflow of INTE. Never set for programs with maturity-level EPISODENHINWEIS."
        maturityLevel:
          $ref: '#/components/schemas/MaturityLevel'
        titel:
          type: string
          example: "Das passende Kopfkissen finden"
          description: "Title of the story."
        lead:
          type: string
          example: "Das Kopfkissen sollte nicht nur kuschelig sein, sondern in erster Linie Kopf und Nacken stützen."
          description: "Lead aka headline of the story."
        moderation:
          type: string
          example: "Christina Scheidegger"
          description: "Name of the host."
        redaktion:
          type: string
          example: "Lukas Schneider"
          description: "Name of the editor."
        geplantePublikationszeitAod:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The planned publication date and time in UTC."
        gueltigkeitAod:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The valid publication date and time in UTC."
        geplanteSendezeit:
          type: string
          format: date-time
          example: "2021-10-11T15:00:00Z"
          description: "The planned distribution time in UTC."
        episodenlauftext:
          type: string
          example: "... langer text ..."
          description: "moderation text"
        blocked:
          type: boolean
          description: "Can the audio be played or not?"
        geoBlocked:
          type: boolean
          description: "Can the audio be played in countries other than Switzerland?"
        image:
          $ref: '#/components/schemas/RokkaIoImage'
        audio:
          $ref: '#/components/schemas/OpenMediaAudio'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/OpenMediaAttachment'
        publicationType:
          $ref: '#/components/schemas/PublicationType'
        beitraege:
          type: array
          items:
            $ref: '#/components/schemas/OpenMediaRunningBeitrag'

    OpenMediaRunningBeitrag:
      description: "Part of a OpenMediaRunning"
      type: object
      required: [ produktElementId ]
      properties:
        produktElementId:
          type: string
          example: "AUDI20230829_RS_0031_0002"
        titel:
          type: string
          example: "Libyens Trauma nach den Fluten"
          description: "Title of the story"
        lead:
          type: string
          example: "Vor einer Woche fegte ein gewaltiger Sturm über die ostlibysche Küste..."
          description: "Lead of the story"
        autor:
          type: string
          example: "Michael Siegenthaler"
          description: "Name of the author"
        image:
          $ref: '#/components/schemas/RokkaIoImage'

    OpenMediaAudio:
      description: "Metadata and reference of the Audio of the program. Not present for Live-products."
      type: object
      required: [ filename, url ]
      properties:
        filename:
          type: string
          example: "AUDI20240506_NR_0013_APP_02.mp3"
          description: "Filename of the uploaded audio-file."
        url:
          type: string
          example: "https://programmrastervorschau-stage.s3.eu-central-1.amazonaws.com/incoming-audio/AUDI20240506_NR_0013/AUDI20240506_NR_0013_APP_02.mp3"
          description: "URL to the storage (Amazon S3) INTE has uploaded the audio-file to."


    OpenMediaAttachment:
      description: "Metadata and reference of the attachments (PDFs, Links) of the program."
      type: object
      required: [ url ]
      properties:
        name:
          type: string
          example: "Kopfkissen Deluxe"
          description: "Public title for the attachment."
        url:
          type: string
          example: "https://programmrastervorschau-stage.s3.eu-central-1.amazonaws.com/additional-assets/AUDI20230623_RS_0015/pdf/20230609_135816_7059_sanapur-magazin-2020.pdf"
          description: "URL to the storage (Amazon S3) INTE has uploaded the media asset to."

    RokkaIoImage:
      description: "Metadata about a image in rokka-io"
      type: object
      required: [ hash, urls, title ]
      properties:
        hash:
          type: string
          example: "1076fce15b5aa26d26a10d303b75186615eeb633"
          description: "the identifier of the image in rokka.io"
        urls:
          type: array
          items:
            $ref: '#/components/schemas/RokkaIoImageUrl'
        title:
          type: string
          example: "Train line"
          description: "Title of the image"
        alternativeTitle:
          type: string
          example: "Train line with city background"
          description: "Alternative title"
        copyright:
          type: string
          example: "copyright"
          description: "the copyright of the image"
        legend:
          type: string
          example: "legend"
          description: "the legend of the image"

    RokkaIoImageUrl:
      description: "Rokka.io image url which can be called with different stacks"
      type: object
      properties:
        stack:
          type: string
          description: "Rokka.io stack for the image"
          example: "square_1_1"
        url:
          type: string
          description: "Rokka.io image url with complete stack and format"
          example: "https://srf-opme.rokka.io/landscape_16_9/1076fce15b5aa26d26a10d303b75186615eeb633.webp"

    MaturityLevel:
      type: string
      description: "The maturity of a OpenMediaRunning"
      nullable: false
      enum:
        - EPISODENHINWEIS
        - ONLINEPUBLIKATION

    PublicationType:
      type: string
      description: "The type of a publication."
      nullable: true
      enum:
        - FILE
        - LIVE
